apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "milvus.fullname" . }}
data:
  milvus.yaml: |+
    {{- include "milvus.config" . | nindent 4 }}

{{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
