apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "milvus.fullname" . }}
data:
  milvus.yaml: |
    {{- include "milvus.serverConfig" . | nindent 4 }}

  {{- if .Values.cluster.enabled }}
  readonly_milvus.yaml: |
    {{- include "milvus.readonly.serverConfig" . | nindent 4 }}
  {{- end }}

{{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
