{{- if and .Values.indexNode.enabled .Values.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus.indexnode.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "indexnode"
{{ include "milvus.ud.labels" . | indent 4 }}
  annotations:
{{ include "milvus.ud.annotations" . | indent 4 }}

spec:
  replicas: {{ .Values.indexNode.replicas }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: "indexnode"
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "indexnode"
{{ include "milvus.ud.labels" . | indent 8 }}
      annotations:
      {{- if .Values.indexNode.profiling.enabled }}
        pyroscope.io/scrape: "true"
        pyroscope.io/application-name: {{ template "milvus.indexnode.fullname" . }}
        pyroscope.io/port: "9091"
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{ include "milvus.ud.annotations" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "milvus.serviceAccount" . }}
      {{- if .Values.image.all.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.all.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.indexNode.heaptrack.enabled }}
      initContainers:
      - name: heaptrack
        command:
        - /bin/bash
        - -c
        - "cp -r /opt/heaptrack /milvus/tools"
        image: "{{ .Values.heaptrack.image.repository }}:{{ .Values.heaptrack.image.tag }}"
        imagePullPolicy: {{ .Values.heaptrack.image.pullPolicy }}
        volumeMounts:
        - mountPath: /milvus/tools
          name: tools
      {{- end }}
      containers:
      - name: indexnode
        image: "{{ .Values.image.all.repository }}:{{ .Values.image.all.tag }}"
        imagePullPolicy: {{ .Values.image.all.pullPolicy }}
        {{- if .Values.indexNode.heaptrack.enabled }}
        args: [ "/milvus/tools/heaptrack/bin/heaptrack", "milvus", "run", "indexnode" ]
        {{- else }}
        args: [ "milvus", "run", "indexnode" ]
        {{- end }}
        env:
        {{- if .Values.indexNode.heaptrack.enabled }}
        - name: LD_LIBRARY_PATH
          value: /milvus/tools/heaptrack/lib:/milvus/lib:/usr/lib
        {{- end }}
        {{- if .Values.indexNode.disk.size.enabled }}
        - name: LOCAL_STORAGE_SIZE
          valueFrom:
            resourceFieldRef:
              divisor: 1Gi
              resource: limits.ephemeral-storage
        {{- end }}
        {{- if .Values.indexNode.extraEnv }}
          {{- toYaml .Values.indexNode.extraEnv | nindent 8 }}
        {{- end }}
        ports:
          - name: indexnode
            containerPort: 21121
            protocol: TCP
          - name: metrics
            containerPort: 9091
            protocol: TCP
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: metrics
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.indexNode.resources | nindent 10 }}
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/default.yaml
          subPath: default.yaml
          readOnly: true
        - name: milvus-config
          mountPath: /milvus/configs/user.yaml
          subPath: user.yaml
          readOnly: true
        {{- if .Values.log.persistence.enabled }}
        - name: milvus-logs-disk
          mountPath: {{ .Values.log.persistence.mountPath | quote }}
          subPath: {{ .Values.log.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- end }}
        - mountPath: /milvus/tools
          name: tools
        {{- if .Values.indexNode.disk.enabled }}
        - mountPath: /milvus/data
          name: disk
        {{- end }}


    {{- if and (.Values.nodeSelector) (not .Values.indexNode.nodeSelector) }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.indexNode.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.indexNode.nodeSelector | indent 8 }}
    {{- end }}
    {{- if and (.Values.affinity) (not .Values.indexNode.affinity) }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.indexNode.affinity }}
      affinity:
{{ toYaml .Values.indexNode.affinity | indent 8 }}
    {{- end }}
    {{- if and (.Values.tolerations) (not .Values.indexNode.tolerations) }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.indexNode.tolerations }}
      tolerations:
{{ toYaml .Values.indexNode.tolerations | indent 8 }}
    {{- end }}

      volumes:
      - name: milvus-config
        configMap:
          name: {{ template "milvus.fullname" . }}
      {{- if .Values.log.persistence.enabled }}
      - name: milvus-logs-disk
        persistentVolumeClaim:
          claimName: {{ .Values.log.persistence.persistentVolumeClaim.existingClaim | default (printf "%s-logs" (include "milvus.fullname" . | trunc 58)) }}
      {{- end }}
      - name: tools
        emptyDir: {}
      {{- if .Values.indexNode.disk.enabled }}
      - name: disk
        emptyDir: {}
      {{- end }}
{{- end }}
