apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "milvus.sharename" . }} # todo: temporoarily ro and wo use the same configfile
data:
  server_config.yaml: |
    {{- include "milvus.serverConfig" . | nindent 4 }}

  log_config.conf: |
    {{- include "milvus.logConfig" . | nindent 4 }}

  {{- if .Values.mishards.enabled }}
  ro_server_config.yaml: |
    {{- include "milvus.roserverConfig" . | nindent 4 }}

  milvus_proxy_config.yaml: |
    {{- include "milvus.proxyconfig" . | nindent 4 }}
  {{- end }}

{{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
