{{- if .Values.mishards.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus.mishards.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "{{ .Values.mishards.name }}"
spec:
  replicas: {{ .Values.mishards.replicas }}
  selector:
    matchLabels:
{{ include "milvus.labels" . | indent 6 }}
      component: "{{ .Values.mishards.name }}"
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "{{ .Values.mishards.name }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      {{- if .Values.mysql.enabled }}
      initContainers:
      - name: "wait-for-mysql"
        image: "{{ .Values.initContainerImage }}"
        command:
        - 'sh'
        - '-c'
        - >
          until nc -z -w 2 {{ .Release.Name }}-mysql 3306 && echo mysql database ok; do
            sleep 2;
          done;
      {{- end }}
{{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
{{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: mishards
        image: "{{ .Values.mishards.image.repository }}:{{ .Values.mishards.image.tag }}"
        imagePullPolicy: {{ .Values.mishards.image.pullPolicy }}
        command:
        - 'sh'
        - '-c'
        - >
            pip install mysqlclient && python mishards/main.py
        ports:
          - name: mishards
            containerPort: 19530
            protocol: TCP
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        resources:
          {{- toYaml .Values.mishards.resources | nindent 10 }}
        volumeMounts:
          - name: mishards-env
            mountPath: /source/mishards/.env
            subPath: mishards_config.yaml
        {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.extraContainers }}
{{ tpl . $ | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: mishards-env
        configMap:
          name: {{ template "milvus.fullname" . }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
