apiVersion: v1
name: milvus
appVersion: "2.0.0-rc.2"
kubeVersion: "^1.10.0-0"
description: Milvus is an open-source vector database built to power AI applications and vector similarity search.
version: 2.0.7
keywords:
  - milvus
  - elastic
  - vector
  - search
  - deploy
home: https://milvus.io/
icon: https://raw.githubusercontent.com/milvus-io/docs/master/v1.0.0/assets/milvus_logo.png
sources:
  - https://github.com/milvus-io/milvus
maintainers:
  - email: zhifeng.zhang@zilliz.com
    name: jeffoverflow
    url: www.zilliz.com
engine: gotpl
