apiVersion: v1
name: milvus
appVersion: "2.2.11"
kubeVersion: "^1.10.0-0"
description: Milvus is an open-source vector database built to power AI applications and vector similarity search.
version: 4.0.26
keywords:
  - milvus
  - elastic
  - vector
  - search
  - deploy
home: https://milvus.io/
icon: https://raw.githubusercontent.com/milvus-io/docs/master/v1.0.0/assets/milvus_logo.png
sources:
  - https://github.com/milvus-io/milvus
maintainers:
  - email: contact@milvus.io
    name: contact
    url: milvus.io
engine: gotpl
