dependencies:
- name: etcd
  version: 8.2.3
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  condition: etcd.enabled
  tags:
    - etcd
- name: minio
  version: 8.0.16
  repository: https://milvus-io.github.io/milvus-helm
  condition: minio.enabled
  tags:
    - minio
- name: pulsar
  version: 2.7.8
  repository: https://pulsar.apache.org/charts
  condition: pulsar.enabled
  tags:
    - pulsar
- name: kafka
  version: 15.5.1
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  condition: kafka.enabled
  tags:
    - kafka
- name: mysql
  version: 8.5.3
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  condition: mysql.enabled
  tags:
    - mysql
