dependencies:
- name: etcd
  version: 6.3.3
  repository: https://charts.bitnami.com/bitnami
  condition: etcd.enabled
  tags:
    - etcd
- name: minio
  version: 8.0.10
  repository: https://milvus-io.github.io/milvus-helm
  condition: minio.enabled
  tags:
    - minio
- name: pulsar
  version: 1.0.31
  repository: https://helm.kafkaesque.io
  condition: pulsar.enabled
  tags:
    - pulsar
